### ISSUE TITLE
CsoundWebAudio examples not working properly

### ISSUE THREAD

**Issue by gogins** [gogins/csound-extended#126]
- [x] Redo `csound_loader.js` to actually work for Android, csound.node, CsoundWebAudio, and CsoundAudioNode. Opening as new issue.
- [x] ALSA is great, but there is choppiness and buzziness in Xanadu with AudioWorklet (CsoundAudioNode) with PulseAudio,
- [x] Dropouts in Xanadu with ScriptProcessorNode (CsoundWebAudio). Nothing I can do about this but it is sorta usable.
- [x] Csound messages not printing with AudioWorklet (CsoundProcessorNode). It turns out the AudioWorklet was probably not even working. I have fixed this.
- [x] Csound is not restartable with ScriptProcessorNode without refreshing the page. I have fixed this by using the default message callback, not the per instance callback.
- [x] The native AudioContext audio format needs to be printed for the user not just the developer. 
- [x] Print loading and startup messages from WebAssembly to the Csound message console.

**Comment by gogins** [comment]
If I break at Start and then resume, the AudioWorklet works, though it's buzzy and noisy. If I don't break, it doesn't work. That suggests Start returns before things are actually working.

**Comment by gogins** [comment]
Trying to recorder connecting and processing in AudioWorklet.

**Comment by gogins** [comment]
Two things to look at:
- [ ] Priority of AudioWorker thread.
- [ ] onprocessaudio going out of scope thanks to garbage collection.

**Comment by gogins** [comment]
This https://developers.google.com/web/updates/2018/06/audio-worklet-design-pattern provides context for these issues. This, frankly, is a real mess.

**Comment by gogins** [comment]
OK, things are getting clearer. I will need to make at least Csound.CompileCsdText and Csound.Start behave as though they are synchronous so that the sequencing always works.

The logic in `csound_loader.js` is very tricky. It was wrong. I think I have mostly fixed it.

CsoundAudioNode is now rendering. But it is still buzzy and choppy.

**Comment by gogins** [comment]
Profiler total times over several seconds of Xanadu:

- CsoundWebAudio: 98.9% in AudioProcessNode.onaudioprocess, 82.3% in Csound$PerformKsmps.

This is hasty, but the implication is that the choppiness is not down to Csound or even to Embind, but to the AudioWorklet infrastructure. As suggested by the worklet design pattern, this is down to using the window message channel ports instead of shared memory.

That being so, the only advantage I see to AudioWorklet at this time is ScriptProcessorNode is deprecated.
- CsoundAudioNode: 87.3% in the AudioWorkletThread process call, 86.3% in Csound$PerformKsmps.

**Comment by gogins** [comment]
Try:

- [ ] Both with and without sync/await pattern.
- [ ] Both with and without shared memory audio buffers.
- [ ]

**Comment by gogins** [comment]
See: https://stackoverflow.com/questions/26150232/resolve-javascript-promise-outside-function-scope.

**Comment by gogins** [comment]
Finally got Csound.CompileCsdText to act as though it is synchronous. This was not easy to understand. First the event handler for the Play button has to be async. Then the CsoundAudioNode.CompileCsdText has to be async with a Promise that assigns its resolve callback to CsoundAudioNode.resolveCompileCsdText.

I'm not sure how to make this consistent with the other JavaScript interfaces to Csound.

**Comment by gogins** [comment]
The other JavaScript interfaces for Csound do not appear to be affected by async/await constructs that are not used. They seem to be simply ignored.

The start/restart problem is fixed. The CsoundAudioNode serialization of calls is fixed. The remaining issues, in order of decreasing importance, are:

- [ ] Choppy audio in CsoundAudioNode.
- [ ] Loss of stdout after the first run in both CsoundAudioNode and CsoundWebAudio (caused by Embind)?
- [ ] Glitches in CsoundWebAudio.
- [ ] Having to run the build script twice.

**Comment by gogins** [comment]
Using emscripten_console_log does not help.

**Comment by gogins** [comment]
Regarding the double run to build... first run:
```
/usr/bin/cmake -E cmake_progress_start /home/mkg/csound-extended/WebAssembly/cmask/CMakeFiles 0
rm: cannot remove 'CMakeCache.txt': No such file or directory
Packaging some resources...
python: can't open file '/tools/file_packager.py': [Errno 2] No such file or directory
Configuring csound-static...
configure: cmake -DCMAKE_VERBOSE_MAKEFILE=1 -DBUILD_PLUGINS_DIR=plugins -DUSE_COMPILER_OPTIMIZATIONS=0 -DWASM=1 -DINIT_STATIC_MODULES=1 -DUSE_DOUBLE=NO -DBUILD_MULTI_CORE=0 -DBUILD_JACK_OPCODES=0 -DEMSCRIPTEN=1 -DCMAKE_TOOLCHAIN_FILE=/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_MODULE_PATH=/cmake -DCMAKE_BUILD_TYPE=Release -GUnix Makefiles -DHAVE_BIG_ENDIAN=0 -DCMAKE_16BIT_TYPE=unsigned short -DHAVE_STRTOD_L=0 -DBUILD_STATIC_LIBRARY=YES -DHAVE_ATOMIC_BUILTIN=0 -DHAVE_SPRINTF_L=NO -DUSE_GETTEXT=NO -DLIBSNDFILE_LIBRARY=../deps/libsndfile.a -DSNDFILE_H_PATH=../deps/libsndfile-1.0.25/src ../../dependencies/csound -DCMAKE_CROSSCOMPILING_EMULATOR="/home/mkg/emsdk/node/12.9.1_64bit/bin/node"
CMake Error at /usr/share/cmake-3.16/Modules/CMakeDetermineSystem.cmake:99 (message):
  Could not find toolchain file: /cmake/Modules/Platform/Emscripten.cmake
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
Making csound-static...
make: make csound-static -j6
make: *** No rule to make target 'csound-static'.  Stop.
```
Second run:
```
```

**Comment by gogins** [comment]
Looks like EMSCRIPTEN_ROOT is undefined or empty on the first run.

**Comment by gogins** [comment]
Configure the build to ignore or fix certain errors:
-Wimplicit-int-float-conversion.
-Wno-dev for CMake.
Fix `emcc:WARNING: Wasm source map won't be usable in a browser without --source-map-base
`.
Fix `/home/mkg/csound-extended/dependencies/cmask/source/parser.cpp:1057:21: warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'? [-Wmismatched-new-delete]`. Nope, I'm leaving that in case it causes a memory leak and I want to know why.

**Comment by gogins** [comment]
I will try an actual callback for the Csound messages. Emscripten supports this with a C API.

**Comment by gogins** [comment]
An actual callback is easy with emscripten::val as a parameter in the CsoundEmbind::SetMessageCallback function.

But again, it works only on the first run.

**Comment by gogins** [comment]
The remaining issues are:

- [ ] Choppy audio in CsoundAudioNode
- [ ] Glitches in CsoundWebAudio.

**Comment by gogins** [comment]
```
Uncaught TypeError: Illegal invocation
    at shim (http://localhost:5103/CsoundAudioProcessor.js:20248:13)
    at __emval_call (http://localhost:5103/CsoundAudioProcessor.js:8851:23)
    at wasm-function[210]:0x7f03f
```
Is this caused by an invalid function, or by an invalid parameter, or both?

**Comment by gogins** [comment]
I have looked at the design pattern HeapAudioBuffer and inspected the current AudioBuffer in the debugger. I do not understand the motivation for the HeapAudioBuffer unless it is simply to skip range checking or to adapt to changes in buffer shape (not an issue here).

**Comment by gogins** [comment]
Regarding the separate Worker pattern, I do not see any reason to do this unless it isolates the audio processing from interruption by other things happening in the browser. But that may be the motivation. I think I will look again at @hlolli's code again and see if it uses this pattern. If so, it confers no significant advantage.

**Comment by gogins** [comment]
Where is this coming from? `audio buffered in 256 sample-frame blocks`. Maybe this is an issue.
`

**Comment by gogins** [comment]
Closing the processor's MessagePort when performance begins does not reduce audio problems.

**Comment by gogins** [comment]
Profiled again. Auto-scrolling the message window is a performance load. I will try not using a message callback at all.

**Comment by gogins** [comment]
Nothing learned from the profile, as it is not easy to interpret the data.

I tried Faust's online Faust compiler and although it's not as bad as our stuff, it is still bad. There is always a repetitive glitch.

**Comment by gogins** [comment]
This issue: https://github.com/WebAudio/web-audio-api/issues/2008 discusses the shared memory design pattern.

**Comment by gogins** [comment]
The experts expect that the processor will listen on the MessagePort just for a start message, then use a SharedArrayBuffer to manage all further communications with the worker.

**Comment by gogins** [comment]
`csound_loader.js` (embedded in `player.html` doesn't work on Android, as it presupposes the WebAssembly code has been loaded. I can try just loading these files, that should work, but better if they're not required. Can .js files be loaded programmatically? Yes, but only asynchronously.

**Comment by gogins** [comment]
CsoundAudioNode just started working perfectly, but I am not sure why. I had assumed it would not work and changed several things at the same time. Check:
Use console.log vs. message callback in csound_loader.js.
csound.node and WebAssembly fight anout NODE vs. WEB, get that fixed.

**Comment by gogins** [comment]
If Csound completes its performance, it will not restart. Change the order of calls.

**Comment by gogins** [comment]
I can't run csound.node in NW.js without PulseAudio. I can run Csound on the command line or in WebAssembly without PulseAudio.
