### ISSUE TITLE
Implement AudioWorklet driver for CsoundWebAudio

### ISSUE THREAD

**Issue by gogins** [gogins/csound-extended#18]

**Comment by gogins** [comment]
See https://developers.google.com/web/updates/2017/12/audio-worklet.

It seems clear that Csound has to run on the audio rendering thread, which has advantages, but must then communicate with the browser or JavaScript context thread by message passing through a port. Otherwise, it seems pretty straightforward.

**Comment by gogins** [comment]
Seems to show how to load WASM in rendering thread:

https://github.com/kripken/emscripten/issues/6230

**Comment by gogins** [comment]
The AudioWorklet design is classic upper half/lower half. In Csound's Start method, first the upper half has to be done in the CsoundAudioWorklet, then the lower half has to be done in the CsoundAudioProcessor. 

Errors have to be sent asynchronously to an error callback.

Some functions can wait for return values using promises.

**Comment by gogins** [comment]
This claims to work but I'm having trouble building/running it:

https://github.com/madChopsCoderAu/WASMAudio

**Comment by gogins** [comment]
See https://github.com/webaudiomodules/webdx7/blob/master/src/dx7-awn.js.

**Comment by gogins** [comment]
I'm now working on modularizing csound-extended's WebAssembly build. Now that I understand how this works:
```
        csound_extended(Module).then(function(Module) {
            console.log("Module: " + Module + " has been loaded.\n");
        });
```
it builds and runs fine.

To use `s SINGLE_FILE` builds and runs, but the `csound_extended.js` file is about 12 (!!) times bigger than the WASM files and takes forever to load... not a good way to go.

**Comment by gogins** [comment]
According to https://github.com/WebAudio/web-audio-api/issues/778, the processor must be defined in a separate file from the node. I'm not sure what is best here as the CMask code is WASM as well as the processor code.

**Comment by gogins** [comment]
https://github.com/google/schism

**Comment by gogins** [comment]
I have both CsoundAudioWorklet and CsoundAudioProcessor working now. The critical steps were:

1. Passing these options to em++: `em++ -v -O1 -std=c++11 --bind --pre-js ../src/CsoundAudioProcessor_prejs.js --post-js ../src/CsoundAudioProcessor_postjs.js -DINIT_STATIC_MODULES=1 -s WASM=1 -s ASSERTIONS=0 -s "BINARYEN_METHOD='native-wasm'" -s LINKABLE=1 -s RESERVED_FUNCTION_POINTERS=1 -s TOTAL_MEMORY=268435456 -s ALLOW_MEMORY_GROWTH=1 -s BINARYEN_ASYNC_COMPILATION=0 -s NO_EXIT_RUNTIME=0 -s SINGLE_FILE=1 -s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]' csound_web_audio.bc libcsound.a ../deps/libsndfile-1.0.25/libsndfile-wasm.a -o CsoundAudioProcessor.js`. In particular, building a single file does the base64 encoding automatically, and turning off asyc compilation is essential.
2. Understanding that my port does not use Transferable arguments, just lists of simple values.

**Comment by gogins** [comment]
Works! _**Scrims**_ now plays. On stopping and restarting, I get this:
```
Uncaught RuntimeError: memory access out of bounds
    at wasm-function[3785]:216
    at wasm-function[3737]:5
    at wasm-function[608]:796
    at wasm-function[5888]:13
    at invoke_ii (http://localhost:5103/CsoundAudioProcessor.js:10737:32)
    at wasm-function[623]:652
    at wasm-function[209]:31
    at wasm-function[394]:114
    at wasm-function[5892]:15
    at dynCall_iii_2293 (eval at makeDynCaller (http://localhost:5103/CsoundAudioProcessor.js:8543:19), <anonymous>:4:12)
<WASM UNNAMED> @ wasm-00c041fa-3785:108
<WASM UNNAMED> @ wasm-00c041fa-3737:4
<WASM UNNAMED> @ wasm-00c041fa-608:371
<WASM UNNAMED> @ wasm-00c041fa-5888:8
invoke_ii @ CsoundAudioProcessor.js:10737
<WASM UNNAMED> @ wasm-00c041fa-623:342
<WASM UNNAMED> @ wasm-00c041fa-209:16
<WASM UNNAMED> @ wasm-00c041fa-394:58
<WASM UNNAMED> @ wasm-00c041fa-5892:9
dynCall_iii_2293 @ VM54:4
Csound$PerformKsmps @ VM173:8
process @ CsoundAudioProcessor.js:11797
```
TODOs include:

1. Setting up real-time/offline rendering is done before connecting the audio graph in Web Audio, but needs to be done after that, in the CsoundAudioProcessor.Start function. Perhaps I can push down the graph startup until after the CsoundAudioProcessor actually starts.
2. Many getters and other lightweight functions should return a value from CsoundAudioProcessor to CsoundAudioNode synchronously.
3. Rendering to soundfile needs to be handled in the context of this asynchrous connection.

**Comment by gogins** [comment]
TODOs include:

1. Setting up real-time/offline rendering is done before connecting the audio graph in Web Audio, but needs to be done after that, in the CsoundAudioProcessor.Start function. Perhaps I can push down the graph startup until after the CsoundAudioProcessor actually starts.
2. Many getters and other lightweight functions should return a value from CsoundAudioProcessor to CsoundAudioNode synchronously.
3. Rendering to soundfile needs to be handled in the context of this asynchrous connection.
4. Messages from CsoundAudioProcessor need to be printed by CsoundAudioNode. _**Done**_.

**Comment by gogins** [comment]
I can now do some performance testing and profiling using _**Scrims**_, as I can increase the tempo until I get breakups.

1. csound_node:
2. csound_web_audio:
3. csound_audio_node:

**Comment by gogins** [comment]
Too many uncontrolled variables with _**Scrims**_, adapting the` cmask.html` example instead. This test works in NW.js if it uses Chrome 66 or later. The instances build up and the time is displayed.

**Comment by gogins** [comment]
Couldn't figure out what to do to throw exceptions mandated by the spec, used RangeError instead.

**Comment by gogins** [comment]
There is a bug where restarting with the audio worklet doesn't work.

**Comment by gogins** [comment]
Anyway it is clear enough that the AudioWorklet implementation runs more _smoothly_ than the ScriptProcessorNode implementation. I need to get it to restart...

**Comment by gogins** [comment]
Ok, just adding simple FM notes up to see how many instances can run without breaking up:

1. csound.node: 243
2. ScriptProcessorNode: 274
3. AudioWorklet: GUI got logy around 500 plus.

**Comment by gogins** [comment]
Trying again with faster note generation. Time to GUI becoming logy.

1. csound.node: 
2. ScriptProcessorNode: 
3. AudioWorklet:

**Comment by gogins** [comment]
Conclusion: CsoundAudioNode, the AudioWorklet + WebAssembly + Embind implementation of Csound for WebAssembly, is done for now.

The AudioWorklet implementation is not actually quite as performant as the other implementations, but does seem run more steadily and to be more resistant to dropouts caused by events in the browser thread. I wonder if it is possible to speed up the AudioWorkletProcessor.process function by not looking at the input unless necessary. I am testing that now.

**Comment by gogins** [comment]
These are the only obvious TODOs:

1. Refactor creation, add separate constructor, etc. to enable running without any input node.
2. Implement some synchronous getters.
